### ISSUE TITLE
All NAs - custom string algorithm

### ISSUE THREAD

**Issue by banamwana** [J535D165/recordlinkage#105]
Have really found this library EXTREMELY useful!

I've been trying to use a edit distance algorithm with approve and disapprove levels as defined in the methodology for the [FRIL project ](http://fril.sourceforge.net/FRIL-Tutorial-3.2.pdf). The following code runs without error, however the comparison scores in comparison_features are all coming up NaN, with the exception of the very first row, which seems to be scoring correctly (using the python implementation of jellyfish damereau-levenshtein distance because of trouble with accented characters)
```

import recordlinkage
from recordlinkage.base import BaseCompareFeature
from jellyfish import damerau_levenshtein_distance as damLev

class EditDistFRIL(BaseCompareFeature):
    
    def _compute_vectorized(self, s1, s2, dLevel = 0.4, aLevel = 0.2):
        
        conc = list(zip(s1, s2))
        
        S1 = str(conc[0]).upper()
        S2 = str(conc[1]).upper()
                    
        eDist = damLev(S1, S2)
        maxLen = max([len(S1), len(S2)])
        
        if eDist > (dLevel * maxLen):
            return pd.Series(float(0))
        
        elif eDist < (aLevel * maxLen):
            return pd.Series(float(1))
        
        else:
            score = (dLevel * maxLen - eDist) / ((dLevel - aLevel) * maxLen)
            return pd.Series(float(score))

compare = recordlinkage.Compare()

compare.string('name', 'name',
                method='damerau_levenshtein', label = 'name')
compare.add(EditDistFRIL('name', 'name1', label = 'name_FR'))

comparison_features = compare.compute(candidate_links, x = clinic, x_link = child)
```

**Comment by J535D165** [comment]
The result of the `_compute_vectorized` should be a `numpy.array` or `pandas.Series` with length `len(s1)`. Your `_compute_vectorized` method returns a Series of length 1. Please have a look at https://github.com/J535D165/recordlinkage/blob/423a2ebb1642ad618581951dfe157585b0ba5fac/recordlinkage/algorithms/string.py#L49
