### ISSUE TITLE
blocking example 

### ISSUE THREAD

**Issue by majamart** [J535D165/recordlinkage#108]
I have some problem with understanding...
I've found text about how works blocking 
![blocked](https://user-images.githubusercontent.com/51406659/61125812-1d554080-a4ab-11e9-88c7-d581c206df0a.png)
 So I understand that this line indexer.add(Block('surname')) divide dataset on lets say cluster where everyone has got the same surname and then in this cluster we compare record by record. 
Here (github )
![example](https://user-images.githubusercontent.com/51406659/61125872-3e1d9600-a4ab-11e9-909c-57c14a7264d9.png)
 I have found example  (example image) and in this example there is a line:
**indexer.add(Block('surname'))**
and then next line
**comparer.add(String('surname', 'surname', method='jarowinkler',
                    threshold=0.85, label='surname'))**

and I dont unerstand why... i have cluster where everone has got the same name and i dont see any reason why in this example compare surname with jarowinkler methos. 

I've thought i understand blocking but now i have big doubt... Can someone explain me ?

**Comment by mayerantoine** [comment]
This blocking code creates the union of the candidate records pair of different blocking key i.e  you have the union of  different cluster (candidate records pair)  1) same surname 2) same given name 3) same soc_id. In that case not all the surname are the same.
In the comparison step you will  create comparison vector , in this case will be binary vector (1,0).
Your feature dataframe will have 1 or 0 when the surname are match or not, based on  jarowinkler.

I think in general your blocking strategy can be different from your comparison strategy. If you block only on surname deciding to include it or not in comparison vector might affect your matching rate depending on the surname data quality.

**Comment by majamart** [comment]
Union explain everything, its even better,  thanks :)
