### ISSUE TITLE
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### ISSUE THREAD

**Issue by Shonexu** [J535D165/recordlinkage#126]
i run into the issue when using recordlinkage library on Python 3.7 & recordlinkage 0.14. Your advice would be highly appreciated

below is the code
============
compare = rl.Compare(candidate_links, df_a, df_b)

below is the full detail of the error message
====================================
ValueError                                Traceback (most recent call last)
<ipython-input-16-181ee39d989a> in <module>
----> 1 compare = rl.Compare(candidate_links, bib, grid)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\recordlinkage\base.py in __init__(self, features, n_jobs, indexing_type, **kwargs)
    540 
    541         # public
--> 542         if n_jobs == -1:
    543             self.n_jobs = cpu_count()
    544         else:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py in __nonzero__(self)
   1476         raise ValueError("The truth value of a {0} is ambiguous. "
   1477                          "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
-> 1478                          .format(self.__class__.__name__))
   1479 
   1480     __bool__ = __nonzero__

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by J535D165** [comment]
This is not the correct way of passing arguments. `Compare` takes no arguments. Example:

```
comp = recordlinkage.Compare()

# initialise similarity measurement algorithms
comp.string('first_name', 'name', method='jarowinkler')
comp.string('lastname', 'lastname', method='jarowinkler')
comp.exact('dateofbirth', 'dob')
comp.exact('sex', 'sex')
comp.string('address', 'address', method='levenshtein')
comp.exact('place', 'place')
comp.numeric('income', 'income')

# the method .compute() returns the DataFrame with the feature vectors.
comp.compute(candidate_pairs, census_data_1980, census_data_1990)
```

I will leave this issue open such that we can add a more informative error on this.

**Comment by Shonexu** [comment]
thanks so much and it explains well indeed. cheers

**Comment by Shonexu** [comment]
Dear Sir,

For the method parameter, May I know what is the full list of available ones besides 'jarowinkler' and 'levenshtein'?

Appreciated of your help
Cheers
Shone
