### ISSUE TITLE
cannot import name 'SKLearnClassifier' from 'recordlinkage.adapters'

### ISSUE THREAD

**Issue by soft-kelly** [J535D165/recordlinkage#127]
There is an import error in `from recordlinkage.adapters import SKLearnClassifier`.
BTW, `from recordlinkage.adapters import KerasAdapter` works for me.

**Comment by J535D165** [comment]
The correct syntax is
```
from recordlinkage.adapters import SKLearnAdapter
```
not
```
from recordlinkage.adapters import SKLearnClassifier
```

Good luck with your RL application.

**Comment by topmenu-kl** [comment]
You should update the docs

https://recordlinkage.readthedocs.io/en/latest/ref-classifiers.html#unsupervised

It state SKLearnClassifier in the imports of the examples
