### ISSUE TITLE
Question on the numerical similarity measure exp 

### ISSUE THREAD

**Issue by GordonAn** [J535D165/recordlinkage#129]
Potential bug/error in
class recordlinkage.compare.Numeric(left_on, right_on, method='linear', offset=0.0, scale=1.0, origin=0.0, missing_value=0.0, label=None)
For the  implemented algorithms   ‘exp’.

 Many thanks for making the very useful package recordlinkage.

While review codes on the numerical similarity measure,
I feel that the implemented algorithm does not agree with the mathematical definition that is in the documentation.
 
According to the text explanation and reference to elasticsearch
https://recordlinkage.readthedocs.io/en/latest/ref-compare.html#module-recordlinkage.compare

https://www.elastic.co/guide/en/elasticsearch/guide/current/decay-functions.html

The exp numerical similarity function is such that
it is an exponential decaying function between 0 and 1 with a flat top. 
Within origin +- offset, it has the value 1. Out side this region, it decay exponentially.

At scale to the left edge or right edge outside  the  offset region, the function decay to 0.5.  See plot in link above
  
Using mathematics pseudo codes, I believe the similarity function should be as follows:

  Let d be the difference between the compared  number pairs (n1, n2) removed from the origin

      d = abs(n1-n2  - origin)

  Based on the graph, the decaying function take the value of 0.5
at  x=scale+offset, relative to the origin, we have

         1/2 = exp(-(offset+scale+origin)*a)

Where a is  the to be  calculated decaying factor.

From this, we have

         log(0.5)= -(offset+scale+origin)*a
       and   a=  -log(0.5)/(offset+scale+origin)

    similarity score = exp(-d*a)

Therefore,

If     (d<=ofsset), 
       set  similarity score=1
      else   
             similarity score = exp(-d*a)

This guarantees, the similarity score=1/2, when d=offset+scale.

However, from   codes, we  have

Recordlinkage.algorithms.numeric

def _exp_sim(d, scale, offset=0, origin=0):

    if offset < 0:
        raise ValueError("The offset must be positive.")

    if scale <= 0:
        raise ValueError("The scale must be larger than 0. ")

    d = (abs(d - origin)).clip(offset, None)

    # solve y=exp(-x*a) if 1/2 = exp(-x/scale)
    expr = '2**(-(d-offset)/scale)'

    return pandas.eval(expr)

The above expression    expr = '2**(-(d-offset)/scale)'  does not  agree with the graph defined  exponential decaying function.

This can be checked easily, namely, whether it gives 1, when within the offset range to origin, and it gives 0.5 and d is at offset+scale away from the origin.

I hope that you have time to take a look at this issue.

**Comment by GordonAn** [comment]
I think that I kind of now understand the implementation.
 expr = '2**(-(d-offset)/scale)'  

It is an exponential function  with base 2 instead of the Euler constant e.
At d=offset, it gives the value of 1
 at (d-offset) = scale, it returns 1/2=0.5

Now the remaining  question is d = (abs(d - origin)).clip(offset, None)
what value does it given for  d-origin < offset,
if it gives offset, then we will get d-offset =0 and the return the score become 1 in the end score.

**Comment by J535D165** [comment]
Thanks for your detailed description. I tried to reproduce the issue by plotting the shape of the similarity algorithms. The shapes look fine to me. Please see the results below. What do you think? 

```
from recordlinkage.algorithms.numeric import _step_sim, _linear_sim, _squared_sim, _exp_sim, _gauss_sim

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
```

```python
arr1 = np.linspace(-5, 5, 100)

plt.plot(arr1, _step_sim(arr1, offset=0, origin=0))
plt.plot(arr1, _linear_sim(arr1, scale=2, offset=0, origin=0))
plt.plot(arr1, _squared_sim(arr1, scale=2, offset=0, origin=0))
plt.plot(arr1, _exp_sim(arr1, scale=2, offset=0, origin=0))
plt.plot(arr1, _gauss_sim(arr1, scale=2, offset=0, origin=0))
plt.show()
```

![graph2](https://user-images.githubusercontent.com/12981139/73611995-14af8d80-45e8-11ea-8460-e6b1c370c762.png)


```python
arr = np.linspace(-8, 12, 100)

plt.plot(arr, _step_sim(arr, offset=2, origin=2))
plt.plot(arr, _linear_sim(arr, scale=2, offset=2, origin=2))
plt.plot(arr, _squared_sim(arr, scale=2, offset=2, origin=2))
plt.plot(arr, _exp_sim(arr, scale=2, offset=2, origin=2))
plt.plot(arr, _gauss_sim(arr, scale=2, offset=2, origin=2))
plt.show()
```
![graph1](https://user-images.githubusercontent.com/12981139/73611981-f77abf00-45e7-11ea-82ae-baa9aaad6ed6.png)

**Comment by GordonAn** [comment]
Many thanks for coming back to my questions. Your plots confirm  that the comparison function is agreeing with the specification and the example plots.

I  understand now how the codes actually  implement  numerical  exponential mathematical function in a clever way!

The first step  d = (abs(d - origin)).clip(offset, None)
             for  abs(d-origin) < offset,
it  gives  offsset,  for  abs(d-origin) >= offset,, the value of d is not changed.

In the second step
expr =  2**(-(d-offset)/scale) 

For    abs(d-origin) < offset
              d= offset,   (d-origin) =0,
expr=2**(0)=1
  This gives the flat top of the curve.

For  abs(d-origin) > offset,  it is a  base 2 exponentiation decay function,
at  
 abs(d-offset0=scale, 
 expr= 2**(-1)=1/2=0.5

So the code is doing exactly, what is supposed to do!

**Comment by J535D165** [comment]
Nevertheless, thanks for reviewing the source code in such detail!
