### ISSUE TITLE
Compare.compute return real score for each metric, not binary `0`/`1` after threshold.

### ISSUE THREAD

**Issue by oyeromenko-ebsco** [J535D165/recordlinkage#159]
Please, add possibility to use real similarity or distance score after `compare.string`  / numeric, etc. So classifier can be trained on more detailed raw data rather than on results obtained from manually set threshold.

**Comment by 44173465VietNHA** [comment]
You can remove "threshold" parameter :)

**Comment by oyeromenko-ebsco** [comment]
Thanks! =)  Did not find it in documentation.

**Comment by jilljenn** [comment]
Same here. Thanks!
