### ISSUE TITLE
Parallel computing (indexing and comparing)

### ISSUE THREAD

**Issue by J535D165** [J535D165/recordlinkage#26]
There is a need for parallel computations in the comparing and indexing modules.

**The current situation:**
- Indexing functions don't use parallel computing. The functions are based on ``pandas`` functions.
- Comparing uses ``numexpr`` if possible. This library performs parallel computing if possible.  
- String similarity functions use the C version of Jellyfish. 

**The desired situation:**
- Split the candidate links in parts and compare in separate processes. 
- Drop numexpr to prevent prevent computing of the library. Replace by 'pandas' parser engine or pure Cython functions
- Use the chunks engine in the ``Index`` class for parallel processes. This might speed up the situation in some cases. 

**To do:**
- Add support for parallel computing in the ``Compare`` class. 
- Drop ``numexpr`` support.
- Add support for parallel computing in the ``Indexing`` class.

**Comment by Jeeva-Ganesan** [comment]
Hi. Has this been completed ? I am using the library at the moment and the` compare_cl.string('') ` is running for more than 4 hours (not completed yet).  Is there a way to speed up the process. I can see that the function is using only one CPU in my instance. (100%). Can we use parallel processing modules like multiprocessing here to speed up the process. I know, my dataset is huge and the comparison makes it running forever. But I am trying to speed up the process.
