### ISSUE TITLE
Version requirement on pandas should be 0.19

### ISSUE THREAD

**Issue by wattse** [J535D165/recordlinkage#29]
`import pandas`
`import recordlinkage`
fails at:
`from pandas.types.inference import is_list_like`
in comparing.py at line 7 with the following error:
ImportError: No module named 'pandas.types.inference'
I ran this on pandas 0.18.1, and the problem ceased to be an issue in version 0.19.1

As far as I can gather, pandas.types.inference.py was added in 0.19.0.

Cheers,
Ed

**Comment by J535D165** [comment]
Thanks a lot! My intention is to let it work with pandas 0.17 and later. I did not realise that `pandas.types.inference` was moved. Working on a fix now. 

There is definitely a need to test against multiple versions of pandas. https://docs.travis-ci.com/user/languages/python/#Testing-Against-Multiple-Versions-of-Dependencies-(e.g.-Django-or-Flask)

**Comment by brydavis** [comment]
Had same issue.  @wattse is right.

`pip install pandas --upgrade` fixes the problem.

Thanks for the code!

**Comment by J535D165** [comment]
Thanks, I am close to a new release now. The next release of the package supports pandas v0.18. 

The package is now tested with TravisCI against multiple versions of pandas.
