### ISSUE TITLE
Problem with Jellyfish

### ISSUE THREAD

**Issue by ajrcre** [J535D165/recordlinkage#30]
When using the string comparison I get
...
/Users/shaharb/.local/lib/python3.5/site-packages/recordlinkage/algorithms/string.py in jaro_winkler_apply(x)
     48 
     49         try:
---> 50             return jellyfish.jaro_winkler(x[0], x[1])
     51         except Exception as err:
     52             if pandas.isnull(x[0]) or pandas.isnull(x[1]):

NameError: ("**name 'jellyfish' is not defined**", 'occurred at index (1, 1)')

Indeed the cjellyfish is missing:
jellyfish.jaro_winkler
<function jellyfish.**cjellyfish**.jaro_winkler>

**Comment by J535D165** [comment]
Thanks for reporting. 

Do you have jellyfish installed? Try: ``import jellyfish``.

**Comment by ajrcre** [comment]
Yes, I have jellyfish imported.
