### ISSUE TITLE
Index KeyError

### ISSUE THREAD

**Issue by spatialbits** [J535D165/recordlinkage#34]
If working with two dataframes that have identical `index_col` names `_blockindex()` in `indexing.py` will produce a key error. 

Line 168 in indexing.py:
```
    # Join
    pairs = data_left.reset_index().merge(
        data_right.reset_index(),
        how='inner',
        left_on=left_on,
        right_on=right_on,
    ).set_index([df_a.index.name, df_b.index.name])
```
will fail because the clashing index column names will have been auto-renamed to "x_column" and "x_column". 

(My index columns are called "ID") -- see debug screenshot. 
![image](https://cloud.githubusercontent.com/assets/4192023/25773787/5c4b5010-325a-11e7-815c-a289e61d22b8.png)

Not a biggie, I just renamed my index columns in the data and carried on. There's maybe another easy way to rename them in the pandas dataframe itself but I haven't looked into it.

**Comment by J535D165** [comment]
Good catch. Will fix it and add tests.
