### ISSUE TITLE
Increase Logging Verbosity

### ISSUE THREAD

**Issue by joelbecker** [J535D165/recordlinkage#39]
Currently, `recordlinkage` logs very few events. However, if more events were logged, users could track the progress of their `recordlinkage` code while it runs, which would be especially useful for large computations which take a long time to run. Events which might be logged could include beginning/ending a new stage (i.e. indexing, comparing, classifying, fusing), and beginning/ending jobs within this stage.

Using the current API, it is easy enough for the user to include logging/print statements in between method calls. However, this will become difficult when the `Pipeline` API is introduced and all major computations are initiated by a single class, and are executed in parallel.

**Comment by J535D165** [comment]
Thanks, I do agree with you. I started working on this today!
