### ISSUE TITLE
Possible bug when len(labels) > 1

### ISSUE THREAD

**Issue by gwerbin** [J535D165/recordlinkage#49]
https://github.com/J535D165/recordlinkage/blob/master/recordlinkage/base.py#L288-L294

```python
        labels = []
        for i in range(0, n_cols):

            label_val = label[i] if label is not None else label_num
            label_num += 1

            labels.append(label_val)

        results[label_val] = c
```

This code creates the list `labels` and then discards it, attempting to assign `c`, which might be a 2D array, to only the final `label_val` column.

What is the correct behavior? My guess is, this:

```python
    if n_cols > 1:
        labels = []
        for i in range(0, n_cols):
            label_val = label[i] if label is not None else label_num
            label_num += 1
            labels.append(label_val)

            results[label_val] = c[:, i]
    else:
        label_val = labels[0]
        if label_val is None:
            label_val = label_num
        label_num += 1

        results[labels[0]] = c
```

Unfortunately you need to handle `n_cols == 1` separately, because you can't assign to multiple columns at once in a DataFrame (I consider this a bug, not sure how the Pandas devs feel about it).

**Comment by J535D165** [comment]
Thanks for reporting this and your work on the PR.

I think the proposed solution is valid. 

One thing to think about is: how should a compare function return 2D (or ND) outputs? I see that it was designed to return a ndarray (or frame). But maybe a tuple of numpy.array's or pandas.Series' is better. This is more consistent with the 2d inputs. Like here: https://github.com/J535D165/recordlinkage/blob/master/recordlinkage/base.py#L275-L276. Nevertheless, your code remains necessary to fix the issue. 

Just curious, can you describe a situation where multiple columns are returned?

**Comment by gwerbin** [comment]
When you want to compute multiple dependent scores off the same result. Here's an example from the code I was using pretty much verbatim:

```python
import cytoolz as tz
import jellyfish as jf
import numpy as np
import recordlinkage as rl
import usaddress

## Make a sample data set

from recordlinkage.datasets import load_febrl1
febrl = load_febrl1()
febrl['street_address'] = febrl['street_number'] + ' ' + febrl['address_1']


## Set up deduplication

def _compare_addrs(addr1, addr2):
    """ Compare address components """
    if not addr1 or not addr2:
        return (np.nan, np.nan)
        
    d = {}
    keys1 = set(addr1)
    keys2 = set(addr2)

    for k in k1 | k2:
        k1 = addr1.get(k)
        k2 = addr2.get(k)
        if not k1 or not k2:
            d[k] = 0
        else:
            d[k] = jf.levenshtein_distance(a, b)
    
    return (len(keys1 & keys2) / min(len(keys1), len(keys2)),
            sum(d.values()) / len(d))

# avoid using decorators so that Joblib pickling works
compare_addrs = tz.compose(np.transpose,
                           np.array,
                           np.vectorize(_compare_addrs, otypes=(float, float)))

comp = rl.Compare(n_jobs=4)
comp.compare_vectorized(compare_addrs, 'addr_components', 'addr_components',
                        label=['addr_overlap', 'addr_dist'])


## Run deduplication

febrl['addr_components'] = febrl['street_address'].map(usaddress.parse, na_action='ignore')
comp.compute(febrl)
```
