### ISSUE TITLE
numpy divide by zero warning

### ISSUE THREAD

**Issue by HumSef** [J535D165/recordlinkage#56]
I am getting the following warning when I run a block indexed match between 2 dataframes.

string.py:151: RuntimeWarning: invalid value encountered in divide
  return np.divide(ab, np.multiply(a, b)).A1

Any thoughts?

**Comment by J535D165** [comment]
Thanks for the report. This warning pops up on the cosine and qgram algorithms. I will take a look. 

The cosine and qgram algorithms are based on _scikit-learn_. The other algorithms use the c implementation of  _jellyfish_. I prefer to rewrite the cosine and qgram algorithms into c.

**Comment by marfox** [comment]
Hi there,

First of all, thanks a lot for this library, it is currently being used in a Wikimedia project for Wikidata: https://github.com/Wikidata/soweego
I'm hitting the same warning when using the cosine algorithm.

@J535D165: as I haven't investigated further, do you think I can safely silence it?

**Comment by J535D165** [comment]
I'm silencing this in #86. This warning is visible when comparing empty strings or missing values. 

```python
In [1]: from recordlinkage.algorithms.string import cosine_similarity                                              
In [2]: import pandas as pd
In [3]: a = pd.Series(["", "test1"])                                                                               
In [4]: b = pd.Series(["", "test2"])                                                                               
In [5]: cosine_similarity(a, b)                                                                                   
RuntimeWarning: invalid value encountered in true_divide
  return np.divide(ab, np.multiply(a, b)).A1

```

**Comment by marfox** [comment]
Sounds good, thanks! Could you please give an estimated time for the next version release that will include #86 ?

**Comment by J535D165** [comment]
New release is on Pypi!

**Comment by marfox** [comment]
FYI, I've been trying the latest release and still getting this warning.
Not a big deal anyway, I'll just add a check on empty strings/missing values.

**Comment by J535D165** [comment]
Hmm, python 3?

**Comment by marfox** [comment]
Yes, tried with versions 3.7.0 and 3.7.2

**Comment by J535D165** [comment]
It was a mistake with the release on Pypi. Version 0.13.2 fixes this. Again thanks for reporting.
