### ISSUE TITLE
Link two datasets: How to Save Results to CSV

### ISSUE THREAD

**Issue by coommark** [J535D165/recordlinkage#62]
Pardon me right from the start. I am new to Python (just a week old, because I have to learn record linking and deduplication for merging e-commerce data). So I guess my question may sound stupid to many.

So I followed the [Link two datasets](http://recordlinkage.readthedocs.io/en/latest/notebooks/link_two_dataframes.html) tutorial, and right now I am sitting here, looking like a restarted monkey, asking myself:

1. How do I save the linked records to CSV?
2. How do I save the unpaired record CSV?

What is next? I see all these bunch of stats but how does it help me from getting fired, seeing that my boss whats me to give him CSVs of linked data and deduplicated data?

Please please help me.

**Comment by dmitriyshashkin** [comment]
If you're not fired yet, try using to_csv method https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html
`matches.to_csv(file_name)`
This library relies on pandas, powerful python library for data manipulation. If you plan to work with data a lot, I'd recommend giving it a try and going through few tutorials.
