### ISSUE TITLE
recordlinkage python

### ISSUE THREAD

**Issue by RamyasriManyala** [J535D165/recordlinkage#68]
input****

import recordlinkage
import pandas as pd
import quandl, math
import numpy as np
import pandas._libs.sparse as splib
from sklearn import preprocessing, cross_validation, svm 
from sklearn.linear_model import LinearRegression
df_a = pd.read_csv("This pc/Downloads/ex.1.csv")
df_b= pd.read_csv("This pc/Downloads/ex2.csv")
indexer = recordlinkage.Index()
indexer.block('surname')
candidate_links = indexer.index(df_a,df_b)
c = recordlinkage.Compare()
c.string('name_a', 'name_b', method='jarowinkler', threshold=0.85)
c.exact('sex', 'gender')
c.date('dob', 'date_of_birth')
c.string('str_name', 'streetname', method='damerau_levenshtein', threshold=0.7)
c.exact('place', 'placename')
c.numeric('income', 'income', method='gauss', offset=3, scale=3, missing_value=0.5)
logrg =recordlinkage.LogisticRegressionClassifier()
logrg.fit(TRAINING_COMPARISON_VECTORS, TRAINING_CLASSES)
logrg.predict(feature_vectors)
ecm = recordlinkage.ECMClassifier()
ecm.fit_predict(feature_vectors)
print(len(matches))

**output******

  File "C:\Users\DELL\AppData\Roaming\Python\Python36\site-packages\scipy\_lib\_ccallback.py", line 1, in <module>
    from . import _ccallback_c

ImportError: cannot import name '_ccallback_c'

**Comment by J535D165** [comment]
This is an issue related to your scipy installation, isn't it? There are some posts on SO. Otherwise, report an issue at the scipy project. 

Regards, Jonathan

**Comment by RamyasriManyala** [comment]
thnq soo much sir.we get rid of that error
