### ISSUE TITLE
record linkage

### ISSUE THREAD

**Issue by RamyasriManyala** [J535D165/recordlinkage#69]
import recordlinkage
import pandas as pd
import pandas._libs.sparse as splib
df_a = pd.read_csv("C:\Users\DELL\Downloads\ex.1.csv")
df_b= pd.read_csv("C:\Users\DELL\Downloads\ex2.csv")
indexer = recordlinkage.Index()
indexer.block('surname')
candidate_links = indexer.index(df_a, df_b)
c = recordlinkage.Compare()
c.string('name_a', 'name_b', method='jarowinkler', threshold=0.85)
c.exact('sex', 'gender')
c.date('dob', 'date_of_birth')
c.string('str_name', 'streetname', method='damerau_levenshtein', threshold=0.7)
c.exact('place', 'placename')
c.numeric('income', 'income', method='gauss', offset=3, scale=3, missing_value=0.5)
logrg =recordlinkage.LogisticRegressionClassifier()
logrg.fit(TRAINING_COMPARISON_VECTORS, TRAINING_CLASSES)
logrg.predict(feature_vectors)
ecm = recordlinkage.ECMClassifier()
ecm.fit_predict(feature_vectors)
print(len(matches))
scikit-learn

output:

  File "C:/Users/DELL/.spyder-py3/record linkage.py", line 4
    df_a = pd.read_csv("C:\Users\DELL\Downloads\ex.1.csv")
                      ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by Pav1777** [comment]
specify the encoding of your csv file, that if it is Utf8 or ascii or byte type. 
Add encoding while reading the file. For example,
df_a = pd.read_csv("C:\Users\DELL\Downloads\ex.1.csv",encoding='utf8')
