### ISSUE TITLE
Q-gram indexing for new API

### ISSUE THREAD

**Issue by SamComber** [J535D165/recordlinkage#76]
Since the migration from `rl.Pairs()` to `rl.Index()` in version 0.12.0 it seems the Q-gram indexing method has been removed. 

Would it be possible to reintroduce this, or was there a reason it's been phased out?

**Comment by J535D165** [comment]
Sorry for the late response, it is removed. The performance was bad. 

You can simulate the behavior by making a full index, compare string with q-gram similarity, and filter pairs on a given threshold. But again, the performance is bad.
