### ISSUE TITLE
excel   files

### ISSUE THREAD

**Issue by ahemanth1990** [J535D165/recordlinkage#80]
how to read excel file in python library

**Comment by pat-earl** [comment]
Assuming you are using the Pandas library, you are probably [looking for this](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html). 

You will need to install another python package to read excel files depending on your development environment. 

Not trying to be a jerk, but for future reference github issues are usually for reserved for bugs found or support with the project itself. There are plenty of resources out there on the internet on how to read an excel file using python, pandas, or whatever you are trying to use. Google will be your best friend and  good luck with your code :-)
