### ISSUE TITLE
wrong duplicate rows count

### ISSUE THREAD

**Issue by shahmilan34** [J535D165/recordlinkage#82]
# CODE:
import recordlinkage
import pandas as pd

data = pd.read_csv("/home/network/new_project/names.csv")

## Indexation step
indexer = recordlinkage.Index()
indexer.block(left_on='my_name')
candidate_links = indexer.index(data)

## Comparison step
compare_cl = recordlinkage.Compare()

compare_cl.exact('my_name', 'my_name', label='my_name')
compare_cl.exact('father_name', 'father_name', label='father_name')
compare_cl.exact('dob', 'dob', label='dob')

features = compare_cl.compute(candidate_links, data)
print(features)

## Classification step
matches = features[features.sum(axis=1) >= 3]
print(len(matches))

# Data:
my_name,father_name,dob
Cooper Adkins,Jarrod Duke,11/24/2019
Kasimir Howell,Paul Pace,04/17/2018
Nathan Moran,Austin Hart,08/24/2018
Fletcher Mcbride,Alexander Branch,04/02/2018
Quentin Parker,Arthur Jimenez,12/07/2018
Kevin Bradley,Dustin Dillard,06/29/2018
Kasimir Boyd,Giacomo Conner,06/02/2018
Brennan Sweet,Leroy Chase,03/16/2019
Mark Pena,Brandon Rivas,07/27/2019
Paul Garrison,Tarik Farley,04/20/2019
Cooper Adkins,Jarrod Duke,11/24/2019
Kasimir Boyd,sdfds Conner,06/02/2018
sdfdfs Moran,Austin Hart,08/24/2018
Cooper Adkins,Jarrod Duke,11/24/2019
Kasimir Boyd,sdfds Conner,06/02/2018

# Expected Result:
len(matches) must be 5 instead of 4
As 
Cooper Adkins,Jarrod Duke,11/24/2019 3x
Kasimir Boyd,sdfds Conner,06/02/2018 2x

# System
Python 3.7.2
recordlinkage 0.12
pandas 0.23.4

**Comment by J535D165** [comment]
The 3 records of Cooper result in 3 links/matches. (A-B, B-C, C-A)
The 2 records of Kasimir result in 1 link/match. (D-E)

See https://en.wikipedia.org/wiki/Complete_graph

**Comment by shahmilan34** [comment]
ok got it.

I have one more issue when i tested your plugin on 50,000 record it is taking too much time:
time for indexing : 1.27 sec
time for comparision(5 exact field for comparision) : 8sec
total time:9.27sec]

how can i reduce time?

**Comment by J535D165** [comment]
Using multiple cores might help https://recordlinkage.readthedocs.io/en/latest/ref-compare.html#recordlinkage.Compare. 

There are also other options, but they require a bit more coding.
