### ISSUE TITLE
Cannot import datasets

### ISSUE THREAD

**Issue by Dragut** [J535D165/recordlinkage#87]
I encountered the following error message when trying to import any of the datasets:
ModuleNotFoundError: No module named 'recordlinkage.datasets'; 'recordlinkage' is not a package
I tried all means but could not solve it. The import recordlinkage itself is fine.

**Comment by J535D165** [comment]
Which version of recordlinkage are you using?

Can you test the following code? If it fails, what's the output?
``` python
In [1]: from recordlinkage.datasets import load_febrl4                                                             

In [2]: df_a, df_b = load_febrl4()                                                                                 

In [3]: import recordlinkage.datasets    
```

**Comment by Dragut** [comment]
Version 0.13. I rerun it today and it comes with data miraculously now.
