### ISSUE TITLE
Possible redundancy of comparing blocking variable in the "linking two datasets" tutorial?

### ISSUE THREAD

**Issue by tim-lan** [J535D165/recordlinkage#90]
Hi there,
I got a specific question about the example of linking two datasets given in the documentation: https://recordlinkage.readthedocs.io/en/latest/notebooks/link_two_dataframes.html#Full-code

According to my understanding, the code uses "given_name" as a blocking variable. Then what is the point of further comparing the "given name" attribute of the two datasets ? Shouldn't the given names of each pair in the candidate links be exactly the same?

**Comment by J535D165** [comment]
Good point! This column will contain ones only. 

Let's remove this comparison. Interested in doing a PR?

**Comment by tim-lan** [comment]
> Good point! This column will contain ones only.
> 
> Let's remove this comparison. Interested in doing a PR?

Thanks for clarifying, Jonathan. I would be happy to do a PR if I know how... I am a browser-based fake Giter.

**Comment by J535D165** [comment]
Ah oke, thanks for reporting!
