### ISSUE TITLE
Pandas deprecation warning

### ISSUE THREAD

**Issue by arthurandres** [J535D165/recordlinkage#99]
I get this warning when running recordlinkage 13.2 with pandas 24.2

`recordlinkage/base.py:288: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.`

To avoid the warning (and the future error) the code should be updated. I don't think using `codes` is backward compatible though. 

I think we can use this issue (and the related PR) for inspiration: https://github.com/apache/arrow/pull/3120/files

I'm happy to help/submit a PR.

**Comment by J535D165** [comment]
Thanks @arthurandres, fixed in PR #103 

For reference: https://github.com/pandas-dev/pandas/issues/13443

**Comment by arthurandres** [comment]
Thanks!
